name: Crear release con instalador al pushear tag de versión

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 2
    steps:      
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-activate-base: true
          activate-environment: ""
      - name: Get version
        id: tagName
        uses: olegtarasov/get-tag@v2.1
      - name: Install dependencies
        run: .\create-env tracker
      - name: Activate environment
        run: conda activate tracker
      - name: Build AntTracker
        run: .\build
      - name: makensis
        uses: joncloud/makensis-action@v3.5
        with:
          script-file: make_installer.nsi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: AntTracker_${{steps.tagName.outputs.tag}}_installer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
